# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mjuicha <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/11/12 14:45:23 by mjuicha           #+#    #+#              #
#    Updated: 2023/12/08 10:58:48 by mjuicha          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRCS	= ft_isalpha.c ft_isdigit.c ft_isalnum.c ft_isascii.c  \
				ft_isprint.c ft_strlen.c ft_memset.c ft_bzero.c ft_memcpy.c  \
				ft_memmove.c ft_strlcpy.c ft_strlcat.c ft_toupper.c ft_tolower.c  \
				ft_strchr.c ft_strrchr.c ft_strncmp.c ft_memchr.c ft_memcmp.c ft_strnstr.c  \
				ft_atoi.c ft_calloc.c ft_strdup.c ft_substr.c ft_strjoin.c ft_strtrim.c ft_split.c  \
				ft_itoa.c ft_strmapi.c ft_striteri.c ft_putchar_fd.c ft_putstr_fd.c ft_putendl_fd.c ft_putnbr_fd.c

SRCB	= ft_lstnew_bonus.c ft_lstadd_front_bonus.c ft_lstsize_bonus.c \
				ft_lstlast_bonus.c ft_lstadd_back_bonus.c

OBJS	= ${SRCS:%.c=%.o}

OBJB	= ${SRCB:%.c=%.o}

NAME	= libft.a 
LIBC	= ar rc
CC		= cc
RM		= rm -f
CFLAGS	= -Wall -Wextra -Werror

%.o :			%.c    libft.h
					${CC} ${CFLAGS} -c $<

all:			${NAME}


${NAME}:		${OBJS}
					${LIBC} ${NAME} ${OBJS}

bonus:			${NAME} ${OBJB}
					${LIBC} ${NAME} ${OBJB}

clean:
					${RM} ${OBJS} ${OBJB}

fclean:			clean
					${RM} ${NAME} ${bonus}

re:				fclean all

.PHONY:			all bonus clean fclean re